name: Unit Test

on:
  pull_request:
    branches: [master]

jobs:
     run_unit_tests:
          runs-on: ubuntu-latest

          steps:
               - name: Checkout Repository
                 uses: actions/checkout@v2

               - name: Install dependencies
                 run: |
                   npm install

               - name: Run linter
                 run: |
                   eslint \"{src,apps,libs,test}/**/*.ts\"
